name: TECHWEBPUC
on:
  push:
    branches: [ main ]

jobs: 
  analyze:
    name: Analise
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix: 
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize SAST
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: SAST Analysis
        uses: github/codeql-action/analyze@v1
      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v2.2.0
      #  with:
      #    node-version: ${{ matrix.node-version }}
      
      #- name: Install dependencies
      #  run: npm install

  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'techwebpuc.com'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo deploy Dev

  deploy-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'techwebpuc.com'
    needs: deploy-dev
    steps:
      - name: Run a one-line script
        run: echo deploy HMG
  
  deploy-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'techwebpuc.com'
    needs: deploy-hmg
    steps:
      - name: Run a one-line script
        run: echo deploy PRD
  
