name: TECHWEBPUC
on:
  push:
    branches: [ main ]

jobs: 
  analyze:
    name: Analise
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix: 
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install

      - name: Build Docker
        run: docker build -t pucweb:2023 .

      - name: Run Docker
        run: docker run -p 3000:3000 pucweb:2023

      - name: Initialize SAST
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: SAST Analysis
        uses: github/codeql-action/analyze@v2
      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v2.2.0
      #  with:
      #    node-version: ${{ matrix.node-version }}
      
      #- name: Install dependencies
      #  run: npm install

  Development:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'techwebpuc.com'
    needs: analyze
    steps:
      - name: Run a one-line script
        run: echo deploy Dev

  staging:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'techwebpuc.com'
    needs: Development
    steps:
      - name: Run a one-line script
        run: echo deploy HMG
  
  production:
    runs-on: ubuntu-latest
    environment:
      name: prd
      url: 'techwebpuc.com'
    needs: staging
    steps:
      - name: Run a one-line script
        run: echo deploy PRD
  
